# Generated by Django 5.1.3 on 2024-12-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_customer_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_data',
            name='user',
        ),
    ]
