# Generated by Django 5.1.3 on 2024-12-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_remove_customer_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Mobile Recharge', 'Mobile Recharge')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('office', models.CharField(blank=True, choices=[('MESCOM', 'MESCOM'), ('HESCOM', 'HESCOM'), ('BESCOM', 'BESCOM'), ('CHESCOM', 'CHESCOM'), ('GESCOM', 'GESCOM')], max_length=10, null=True)),
                ('water_office', models.CharField(blank=True, choices=[('Mangaluru', 'Mangaluru'), ('Bengaluru', 'Bengaluru'), ('Mysuru', 'Mysuru')], max_length=20, null=True)),
                ('mobile_service_provider', models.CharField(blank=True, choices=[('Jio', 'Jio'), ('BSNL', 'BSNL'), ('Airtel', 'Airtel')], max_length=20, null=True)),
                ('consumer_number', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.customer_data')),
            ],
        ),
    ]
