# Generated by Django 5.1.3 on 2024-12-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_billpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='consumer_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Transfer', 'Transfer'), ('Bill Payment', 'Bill Payment')], max_length=20),
        ),
    ]
