# Generated by Django 5.1.3 on 2024-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_alter_billpayment_consumer_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
