# Generated by Django 5.1.3 on 2024-12-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_electricitypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('Mangaluru', 'Mangaluru'), ('Bengaluru', 'Bengaluru'), ('Mysuru', 'Mysuru')], max_length=50)),
                ('consumer_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.customer_data')),
            ],
        ),
    ]
