# Generated by Django 5.1.3 on 2024-12-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0010_waterpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileRechargePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(choices=[('Jio', 'Jio'), ('BSNL', 'BSNL'), ('Airtel', 'Airtel')], max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recharged_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.customer_data')),
            ],
        ),
    ]
