# Generated by Django 5.1.3 on 2024-12-11 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0015_remove_transaction_mobile_recharge_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mobile_recharge_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bank.mobilerechargepayment'),
        ),
    ]
