# Generated by Django 5.1.3 on 2024-12-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0018_transaction_electricity_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='electricity_payment',
        ),
    ]
